[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.example.com/:splat"
  status = 200

[[headers]]
  for = "/node_modules/ace-builds/src-noconflict/*"
  [headers.values]
    Content-Type = "application/javascript"
